# Generated by Django 3.1.7 on 2021-11-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marca',
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.marca'),
        ),
    ]
