# Generated by Django 3.1.7 on 2021-11-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='ciudad',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='direccion',
            new_name='cellphone',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='estado',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='nombre_comercial',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='nombre_empresa',
            new_name='name_commerce',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='pais',
            new_name='name_company',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='telefono',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='sitio_web',
            new_name='website',
        ),
    ]
