# Generated by Django 3.1.7 on 2021-11-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20211102_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='marca',
            field=models.ManyToManyField(to='stores.Marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
