# Generated by Django 3.1.7 on 2021-11-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20211102_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
